application: secretsanta-jshieh
version: 6
runtime: python
api_version: 1

handlers:

# static directories
- url: /stylesheets
  static_dir: stylesheets
- url: /javascript
  static_dir: javascript
- url: /images
  static_dir: images

# static files
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

# pages
- url: /
  script: main.py
- url: /create
  script: main.py
- url: /manage
  script: main.py
- url: /signup
  script: main.py
- url: /facebook/
  script: main.py

# static pages
- url: /about
  script: main.py
- url: /faq
  script: main.py
- url: /terms
  script: main.py
- url: /privacy
  script: main.py
- url: /sitemap
  script: main.py

# operate and redirect
- url: /save/details
  script: main.py
- url: /remove/invitee
  script: main.py
- url: /remove/participant
  script: main.py
- url: /add/participant
  script: main.py
- url: /add/invitee
  script: main.py

# asyncs
- url: /save/invitation_message
  script: main.py

# email handlers
- url: /email/creation
  script: main.py
- url: /email/invitation
  script: main.py
- url: /email/message
  script: main.py
- url: /email/assignment
  script: main.py
- url: /email/notification
  script: main.py
- url: /post/public_message
  script: main.py

# taskqueue tasks
- url: /tasks/email/creation
  script: main.py
- url: /tasks/email/invitation
  script: main.py
- url: /tasks/email/message
  script: main.py
- url: /tasks/email/assignment
  script: main.py
- url: /tasks/email/notification
  script: main.py
- url: /tasks/email/reminder
  script: main.py
- url: /tasks/email/public_message
  script: main.py

# cron jobs
- url: /tasks/generate/assignments
  script: main.py
- url: /tasks/email/reminders
  script: main.py

# default catch-all
- url: /.*
  script: not_found.py
