application: secretsanta-jshieh
version: 2
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /javascript
  static_dir: javascript
- url: /images
  static_dir: images
- url: /
  script: main.py
- url: /confirm
  script: main.py
- url: /email
  script: main.py
- url: /manage
  script: main.py
- url: /.*
  script: not_found.py
